export const DEBUG = false;

export const SET_CHUNK_INDEX = "SET_CHUNK_INDEX";
export const SET_ERROR_CORRECTION_LEVEL = "SET_ERROR_CORRECTION_LEVEL";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const SET_FILE = "SET_FILE";
